const actionTypes = {
  SET_CURRENCY_UNIT: "SET_CURRENCY_UNIT",
  ADD_TO_CART: "ADD_TO_CART",
  TOGGLE_CART_OVERLAY: "TOGGLE_CART_OVERLAY",
  INCREMENT_ITEM_QUANTITY: "INCREMENT_ITEM_QUANTITY",
  DECREMENT_ITEM_QUANTITY: "DECREMENT_ITEM_QUANTITY",
  SET_MODAL_PRODUCT: "SET_MODAL_PRODUCT",
  CLOSE_MODAL_PRODUCT: "CLOSE_MODAL_PRODUCT",
  GET_FILTERED_PRODUCTS: "GET_FILTERED_PRODUCTS",
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
};

export default actionTypes;
